### ISSUE TITLE
Erro when running

### ISSUE THREAD

**Issue by elmor34** [webmatze/angular-jspm-mobx-starter-project#3]
When run, get the following error with no display
Any idea for msissing item ?

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module testapp due to:
Error: [$injector:modulerr] Failed to instantiate module {"version":{"full":"1.0.6"}} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object
http://errors.angularjs.org/1.5.0/ng/areq?p0=module&p1=not%20a%20function%2C%20got%20Object
    at eval (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:71:12)
    at assertArg (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:1828:11)
    at assertArgFn (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:1838:3)
    at eval (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:4515:11)
    at forEach (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:324:20)
    at loadModules (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:4490:5)
    at eval (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:4507:40)
    at forEach (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:324:20)
    at loadModules (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:4490:5)
    at createInjector (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:4412:19)
http://errors.angularjs.org/1.5.0/$injector/modulerr?p0=%7B%22version%22%3A…ckages%2Fgithub%2Fangular%2Fbower-angular%401.5.0%2Fangular.js%3A4412%3A19)
    at eval (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:71:12)
    at eval (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:4529:15)
    at forEach (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:324:20)
    at loadModules (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:4490:5)
    at eval (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:4507:40)
    at forEach (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:324:20)
    at loadModules (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:4490:5)
    at createInjector (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:4412:19)
    at doBootstrap (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:1694:20)
    at bootstrap (http://localhost:3000/jspm_packages/github/angular/bower-angular@1.5.0/angular.js:1715:12)
http://errors.angularjs.org/1.5.0/$injector/modulerr?p0=testapp&p1=Error%3A…ckages%2Fgithub%2Fangular%2Fbower-angular%401.5.0%2Fangular.js%3A1715%3A12)
```

**Comment by webmatze** [comment]
That seemed to be a problem with the bower version of angular and angular-material. I switched to the npm versions instead.
Thank you for reporting the error.
